defaults:
  - _self_
  - task: pt

# Experiment args
mode: 'pt'
device: gpu
eval_only: false
predict_only: false
seed: 2137

model:
  name: 'google/t5-v1_1-base'
  checkpoint_path: ''
  dropout: 0.0
  random_init: true
  compile: false # Pytorch 2.0
  no_plus: false

data:
  input_length: 512
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  num_workers: 8

optim:
  name: adamwscale
  base_lr: 2e-2
  batch_size: 144
  total_steps: 65536
  epochs: -1 # If it's > 0 it overwrites total_steps
  warmup_steps: 10000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 2
  final_cosine: 1e-5

eval:
  every_steps: 5000
  steps: 10000000

pred:
  every_steps: 10000000
  every_epochs: 0

checkpoint:
  every_steps: 5000
  every_epochs: 0

logging:
  wandb: false
  wandb_project: 'biot5_plus'
  wandb_group: 'pt'
  wandb_run_name: 'pt'
  neptune: false
  neptune_creds:
    project:
    api_token:
    tags:
  every_steps: 100
  grad_l2: true
  weights_l2: true

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/debug_${now:%H-%M-%S}

molecule_dict: ../dict/selfies_dict_0523.txt
pair_data_dir: ~/biot5_plus/unimpt
pubmed_data_dir: ~/biot5_plus/pubmed/pmc_hf_dataset/pmc_all_cleaned
incontext_pubmed_data_dir: ~/biot5_plus/pubmed/annotation_v1.1_replaced_name_iupac_selfies_prob
incontext_biorxiv_data_dir: ~/biot5_plus/unimpt/biorxiv_bern2_name_iupac_selfies_prob
run_test: True
run_validation: True
finetune_from_biot5: ''

generation_config:
  do_sample: false
  num_beams: 1
  temperature: 1.0
  top_k: 50
  top_p: 1.0
  repetition_penalty: 1.0
  max_new_tokens: ''

restore_train: False
restore_train_path: ~/tmp/checkpoint-pt-xxxx