# @package _global_

mode: 'ft'

data:
  max_seq_len: 512
  max_target_len: 512
  max_num_instances_per_task: 10000000 # TODO
  add_task_name: False
  add_task_definition: False # TODO
  num_pos_examples: 0
  num_neg_examples: 0
  add_explanation: False
  tk_instruct: False
  exec_file_path: utils/molinst_ni_dataset.py
  data_dir: ~/tmp
  task_dir: ~/tmp

optim:
  name: adamw
  base_lr: 1e-3
  batch_size: 128
  epochs: -1
  total_steps: 50000
  warmup_steps: 1000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 0.0
  grad_acc: 8
  test_bsz_multi: 1

eval:
  every_steps: 1000
  steps: 100000 # whole test set

pred:
  every_steps: 1000

checkpoint:
  every_steps: 2000

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/finetune_mol2text_local

test_task: mol2text
result_fn: test_pred.tsv